# Generated by Django 5.1.7 on 2025-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransExpress1App', '0002_quote_delete_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
