# Generated by Django 4.2 on 2025-03-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransExpress1App', '0003_alter_quote_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=255)),
                ('delivery', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
